b3da_gallery:
    resource: "@b3daGalleryBundle/Controller/"
    type:     annotation
    prefix:   /

oneup_uploader:
    resource: .
    type: uploader

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
